### ISSUE TITLE
GIthub project setup enhancement

### ISSUE THREAD

**Issue by adiSuper94** [RoadTripppin/wazzup#17]

**Comment by adiSuper94** [comment]
Added WIP plugin to our Org.
https://github.com/marketplace/wip
Check it out.

**Comment by adiSuper94** [comment]
@RoadTripppin/all 

- [ ]  @shashankbhat10 
- [ ]  @ashwin2303 
- [ ]  @AdishRao

**Comment by ashwin2303** [comment]
@adiSuper94  Completed the setup and hence closing the ticket.
