### ISSUE TITLE
We don't have a 'username' just the user's name:

### ISSUE THREAD

**Issue by AdishRao** [RoadTripppin/wazzup#22]
We don't have a 'username' just the user's name:
ex: Adish Rao
not:
adishrao

_Originally posted by @AdishRao in https://github.com/RoadTripppin/wazzup/pull/19#discussion_r800898525_

**Comment by ashwin2303** [comment]
I have pulled this into the sprint and will fix the issue.

**Comment by ashwin2303** [comment]
The issue is resolved and the code is checked in to the master branch.
