### ISSUE TITLE
User logs in with their email id and password. We do not have a username.

### ISSUE THREAD

**Issue by AdishRao** [RoadTripppin/wazzup#23]
As discussed while creating user stories, the user logs in with their email id and password. We do not have a username.

_Originally posted by @AdishRao in https://github.com/RoadTripppin/wazzup/pull/19#discussion_r800899168_

**Comment by ashwin2303** [comment]
I have pulled this into the sprint and will fix the issue.

**Comment by ashwin2303** [comment]
We have removed the username and added email. Tested using postman and is working as expected.
